Hello: Hello
AllListsTitle: All Lists
NoListsYet: You haven't created any lists yet. 

ListNameLabel: List Name
PleaseEnterListName: Please Enter a Name for the New List
PleaseEnterListEntryName: Please Enter a Name for the New List Entry
CreateNewListButton: Create
CreateNewListEntryButton: Add
EditListEntryButton: Save Changes
ListAccessDenied: You do not have permission to access this list.

ListEntryLabel: List Entry Name:

EditItem: Edit
DeleteItem: Delete
