WriteMeAList: WriteMeAList.com
Welcome: Welcome to
WhyWMAL: Have you ever wanted to leave but needed to get a list of items to buy or tasks to do before you left? Now you can leave and tell the other people to just send you a list using
AllListsTitle: All Lists
ListTitle title@Text: #{title}
NoListsYet: You haven't created any lists yet. 
YourLists: Your Lists
GotoYourLists: My Lists

LoginBlurb: If you already have an account, login here:
NewAccountBlurb: If you don't yet have an account, create one using either your Yahoo or Google Account information. We do not collect your personal information. Yahoo returns only a unique ID, there is no identifying information included. Google only returns your e-mail address. We have not and will not ever sell your e-mail address.

ListNameLabel: List Name
EnterListName: Please enter a name for the new list
EnterListItemName: Please enter a name for a new list entry
CreateListHeading: Create a New List:
CreateListButton: New List
CreateListItemButton: Add To List
EditListItemButton: Save Changes
ListAccessDenied: You do not have permission to access that list.

ListItemCreateLabel:
ListItemEditLabel: Edit the list item name:
EditEntryHeader listName@Text: Edit entry in list "#{listName}"

CreateShareLink: Create Share Link
EditItem: Edit
DeleteItem: Delete
CompleteItem: Complete
