WriteMeAList: WriteMeAList.com
Welcome: Welcome to
WhyWMAL: Have you ever wanted to leave but needed to get a list of items to buy or tasks to do before you left? Now you can leave and tell the other people to just send you a list using
ListTitle title@Text: #{title}
NoListsYet: You haven't created any lists yet. 

AllLists: All Lists
GotoAllLists: All Lists
AllListsTitle: All Lists

LoginLink: Login
LogoutLink: Logout
LoginBlurb: If you already have an account, login here:
NewAccountBlurb: If you don't yet have an account, create one using either your Yahoo or Google Account information. We do not collect your personal information. Yahoo returns only a unique ID, there is no identifying information included. Google only returns your e-mail address. We have not and will not ever sell your e-mail address.


ListNameLabel: List Name
EnterListName: Please enter a name for the new list
EnterListItemName: Please enter a name for a new list entry
CreateListHeading: Create a New List:
CreateListButton: New List
CreateListItemButton: Add To List
EditListItemButton: Save Changes
ListAccessDenied: You do not have permision to access that list.

NoListItems: You have not added any items to this list yet. Please add to the list by typing the name of an item or task in the box above and clicking "Add To List"
ListItemCreateLabel:
ListItemCategoryLabel: Category
ListItemEditLabel: Edit the list item name:
EditEntryHeader listName@Text: Edit entry in list "#{listName}"

CreateAccount: Create Account
EditItem: Edit
DeleteItem: Delete
CompleteItem: Complete

UseFormBelowToCreateLists: Please use the form below to create your first list. Alternately, if someone mailed you a link to a list, please click on that link to add the list they shared with you to your account.
