Default: &defaults
  user: writemealist
  password: writemealist
  host: localhost
  port: 27017
  database: writemealist
  connections: 10

Development:
  <<: *defaults

Testing:
  database: writemealist_test
  <<: *defaults

Staging:
  database: writemealist_staging
  connections: 100
  <<: *defaults

Production:
  database: writemealist_production
  connections: 100
  host: localhost
  <<: *defaults
